
language: node_js

sudo: false

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"

notifications:
  slack: dide-hiv:lZajIW2gCbXMYVgXkp1Bu1ii
  email:
    on_success: change
    on_failure: change
